services:
  www:
    container_name: www
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      BASE_URL: ${BASE_URL}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: always
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - traefik_default
    labels:
      - traefik.enable=true
      - traefik.http.routers.lovely_www.entrypoints=websecure
      - traefik.http.routers.lovely_www.tls=true
      - traefik.http.routers.lovely_www.tls.certresolver=production
      - traefik.http.routers.lovely_www.rule=Host(`lovely.clement-jny.fr`)
      - traefik.http.services.lovely_www.loadbalancer.server.port=80

  mysql:
    container_name: mysql
    image: mysql:lts # 8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - ${MYSQL_HOST_PORT}:${MYSQL_DOCKER_PORT}
    restart: always
    networks:
      - traefik_default

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.1
    environment:
      PMA_HOST: ${DB_HOST}
    ports:
      - ${PMA_HOST_PORT}:${PMA_DOCKER_PORT}
    links:
      - mysql
    depends_on:
      - mysql
    restart: always
    networks:
      - traefik_default

volumes:
  mysql_data:
    driver: local

networks:
  traefik_default:
    external: true
